name: CI

on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt install extra-cmake-modules qtbase5-dev
    - name: Configure build
      working-directory: build
      run: cmake ..
    - name: Build
      working-directory: build
      run: make
    - name: Run tests
      working-directory: build
      run: ctest --verbose
