name: CI

on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt install extra-cmake-modules qtbase5-dev
    - name: Configure build
      run: mkdir build && cd build && cmake ..
    - name: Build
      working-directory: build
      run: make
    - name: Run tests
      working-directory: build
      run: ctest --verbose
  
  foobar:
    runs-on: ubuntu-latest
    name: "Foobar, dawg!"
    strategy:
      matrix:
        pal: ["guy", "friend"]
    steps:
      - name: Shout out
        run: echo "I'm not your ${{ matrix.pal }}, buddy"
