name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install kate
      run: sudo apt install kate
    - name: Run a one-line script
      run: echo Oh hi Mark!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Foo
      run: echo "Bar"
